services:
  fabric_management_1:
    build:
      context: /workspace/WireGenie/
      dockerfile: environment/wireguard_fabric/Dockerfile
    entrypoint: [ "python3", "-m", "wire_fabric", "management-server", "--name", "newton", "--host", "0.0.0.0", "--port", "8001", "--network", "10.0.0.0/24", "--public-ip", "172.30.30.11"]
    ports:
      - 8001:8001
    volumes:
      - /workspace/WireGenie:/wireguard_fabric
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      internet:
        ipv4_address: 172.30.30.11

  fabric_management_2:
    build:
      context: /workspace/WireGenie/
      dockerfile: environment/wireguard_fabric/Dockerfile
    entrypoint: [ "python3", "-m", "wire_fabric", "management-server", "--name", "venus", "--host", "0.0.0.0", "--port", "8001", "--network", "10.0.0.0/24", "--public-ip", "172.30.30.12", "--management-servers-list", "172.30.30.11:8001"]
    volumes:
      - /workspace/WireGenie:/wireguard_fabric
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    depends_on:
      - fabric_management_1
    networks:
      internet:
        ipv4_address: 172.30.30.12

  fabric_management_3:
    build:
      context: /workspace/WireGenie/
      dockerfile: environment/wireguard_fabric/Dockerfile
    entrypoint: [ "python3", "-m", "wire_fabric", "management-server", "--name", "emperor", "--host", "0.0.0.0", "--port", "8001", "--network", "10.0.0.0/24", "--public-ip", "172.30.30.13"]
    # Then run the below code to join fabric_management_1
    # /usr/bin/env /home/gitpod/.pyenv/shims/python -m wire_fabric client join --host 172.30.30.13 --port 8001 --token eyJpcCI6ICIxNzIuMzAuMzAuMTEiLCAicG9ydCI6IDgwMDF9
    volumes:
      - /workspace/WireGenie:/wireguard_fabric
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    depends_on:
      - fabric_management_1
    networks:
      internet:
        ipv4_address: 172.30.30.13

  # fabric_peer_1:
  #   build:
  #     context: /workspace/WireGenie/
  #     dockerfile: environment/wireguard_fabric/Dockerfile
  #   volumes:
  #     - /workspace/WireGenie:/wireguard_fabric
  #   ports:
  #     - 8000:8000
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_MODULE
  #   networks:
  #     internet:
  #       ipv4_address: 172.30.30.111

  # fabric_peer_2:
  #   build:
  #     context: /workspace/WireGenie/
  #     dockerfile: environment/wireguard_fabric/Dockerfile
  #   volumes:
  #     - /workspace/WireGenie:/wireguard_fabric
  #   ports:
  #     - 8000:8000
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_MODULE
  #   networks:
  #     internet:
  #       ipv4_address: 172.30.30.112


networks:
  internet:
    ipam:
      driver: default
      config:
        - subnet: 172.30.30.0/24
          gateway: 172.30.30.1