services:
  node_1:
    build:
      context: .
      dockerfile: Dockerfile
    # stdin_open: true # Keep stdin open even if not attached
    # tty: true        # Allocate a pseudo-TTY
    container_name: node_wg_1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./config/node_1:/config
    env_file: .env
    networks:
      site_1:
      internet:
        ipv4_address: 172.30.30.2

  node_2:
    build:
      context: .
      dockerfile: Dockerfile
    # stdin_open: true # Keep stdin open even if not attached
    # tty: true        # Allocate a pseudo-TTY
    container_name: node_wg_2
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./config/node_2:/config
    env_file: .env
    networks:
      site_2:
      internet:
        ipv4_address: 172.30.30.3

networks:
  site_1:
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/24
          gateway: 172.10.0.1

  site_2:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1

  internet:
    ipam:
      driver: default
      config:
        - subnet: 172.30.30.0/24
          gateway: 172.30.30.1

